[package]
name = "noisette"
version = "0.1.0"
edition = "2021"
description = "A library for generating 2D noise functions with analytical gradients"
license = "MIT"

[dependencies]
nalgebra = "0.33.2"
ndarray = "0.16.1"
rand = "0.9.0"

[dev-dependencies]
ndarray_images = "0.0.0"
