[package]
name = "noisette"
version = "0.0.0"
edition = "2021"
description = "A simple library for generating 2D noise"
license = "MIT"

[dependencies]
nalgebra = "0.33.2"
ndarray = "0.16.1"
rand = "0.8.5"

[dev-dependencies]
ndarray_images = "0.0.0"
